drop table RECETTE IF EXISTS;
create table RECETTE
(
   ID_RECETTE NUMBER NOT NULL AUTO_INCREMENT,
   NOM_RECETTE varchar2(50) not null,
   MIN_PAR_POR DECIMAL(8,2) NOT NULL,
   VIT_PAR_POR DECIMAL(8,2) NOT NULL,
   TEMPS_PREPA DECIMAL(4) NOT NULL,
   primary key(ID_RECETTE)
);

drop table INSTRUCTION IF EXISTS;
create table INSTRUCTION
(
	ID_INSTRUCTION NUMBER NOT NULL AUTO_INCREMENT,
	CHRONO NUMBER NOT NULL,
	LIBELLE varchar2(255) NOT NULL,
	ID_RECETTE NUMBER NOT NULL,
	primary key(ID_INSTRUCTION),
	FOREIGN KEY (ID_RECETTE) REFERENCES RECETTE(ID_RECETTE)
);


drop table INGREDIENT IF EXISTS;
create table INGREDIENT
(
	ID_INGREDIENT NUMBER NOT NULL AUTO_INCREMENT,
	LIBELLE VARCHAR2(50) NOT NULL,
	UNITE_MESURE VARCHAR2(2) NOT NULL,
	VITAMINES DECIMAL(8,2) NOT NULL,
	MINERAUX DECIMAL(8,2) NOT NULL,
	PRIMARY KEY(ID_INGREDIENT)
);

drop table RECETTE_INGREDIENT IF EXISTS;
create table RECETTE_INGREDIENT
(
	ID_RECETTE NUMBER NOT NULL,
	ID_INGREDIENT NUMBER NOT NULL,
	QUANTITE NUMBER NOT NULL,
	FOREIGN KEY (ID_RECETTE) REFERENCES RECETTE(ID_RECETTE),
	FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT)
);


INSERT INTO RECETTE(NOM_RECETTE, MIN_PAR_POR, VIT_PAR_POR,
   TEMPS_PREPA)
 VALUES ('Lasagnes', 50, 37, 120);

INSERT INTO INGREDIENT(LIBELLE,UNITE_MESURE,VITAMINES,MINERAUX) 
 VALUES ('Pomme de terre', 'mg', 150.46, 20.45);





